project:
  type: website
  output-dir: docs
  render:
    - "README.md"
    - "!/code/jupyter/redcap.ipynb"
    - "*.qmd"
    - "*.md"
    - "/data/**/*.ipynb"



website:
  title: "Research Data Management"
  navbar:
    search: true
    left:
      - text: "Home"
        href: README.md
  open-graph: true
  sidebar:
    style: "docked"
    contents: auto
  reader-mode: true
  repo-url: https://github.com/pranavmishra90/courses-by-mishra-tmp
  repo-actions: [issue]
  page-footer: "Copyright 2024: Pranav Kumar Mishra"


bibliography:
  - ./notebook/references.bib
csl: ./notebook/ama.csl

citation: false
google-scholar: true


execute:
  freeze: auto




affiliations:
  - id: rushortho
    name: Dept of Orthopedic Surgery, Rush University
    department: Orthopedic Surgery
    city: Chicago
    region: IL
    country: USA
    postal-code: 60612
    affiliation-url: https://rushu.rush.edu
    
  - id: rushsurg
    name: Dept of Surgery, Rush University
    department: Surgery
    address: 1735 W Harrison St, Ste 563
    city: Chicago
    region: IL
    country: USA
    postal-code: 60612
    affiliation-url: https://rushu.rush.edu

  - id: rushpeds
    name: Dept of Pediatrics, Rush University
    department: Pediatrics
    address: 1735 W Harrison St, Ste 563
    city: Chicago
    region: IL
    country: USA
    postal-code: 60612
    affiliation-url: https://rushu.rush.edu

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-depth: 3
    lang: en-US
    email-obfuscation: javascript
    code-fold: true
    code-line-numbers: true
    code-overflow: wrap
    grid:
      sidebar-width: 300px
      body-width: 900px
    default-image-extension: svg
    embed-resources: true
  pdf:
    # pdf-engine: latexmk
    documentclass: scrartcl
    toc: true
    code-fold: true
    papersize: letter
    toc-depth: 2
    margin-left: 30mm
    margin-right: 30mm
    highlight-style: github
    colorlinks: true
    default-image-extension: png 